#!/bin/bash

# Specify the file(s) or directory to be added
git add <file_or_directory>

# Commit with the provided command-line arguments as the commit message
git commit -m "${*:1}"

# Push the committed changes to the remote repository
git push

